services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantumtec-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://qt_db_tc9w_user:f1Qzpl6lszxpFrOs0VWTu7JL2xpL3vmH@dpg-d49v8c9e2q1c73dsn96g-a.oregon-postgres.render.com/qt_db_tc9w
      JWT_SECRET: quantumtec_secret_2025
      JWT_EXPIRES_IN: 24h
      NODE_ENV: production
      PORT: 5000
    volumes:
      - ./public/certificates:/app/public/certificates
    restart: unless-stopped
